/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SceneSetup;

/**
 *
 * @author jalpd
 */
public class GameInstructions extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    private OptionPanel optionPanel;

    public GameInstructions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.optionPanel = optionPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aImage = new javax.swing.JLabel();
        aDescription = new javax.swing.JLabel();
        dImage = new javax.swing.JLabel();
        dDescription = new javax.swing.JLabel();
        sImage = new javax.swing.JLabel();
        sDescription = new javax.swing.JLabel();
        wImage = new javax.swing.JLabel();
        wDescription = new javax.swing.JLabel();
        mainTitle = new javax.swing.JLabel();
        spaceImage = new javax.swing.JLabel();
        spaceDescription = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        aImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\jalpd\\Downloads\\BombermanFinal(1)\\BombermanFinal\\payload\\Keys\\a.png")); // NOI18N

        aDescription.setText("Move Left");

        dImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\jalpd\\Downloads\\BombermanFinal(1)\\BombermanFinal\\payload\\Keys\\d.png")); // NOI18N

        dDescription.setText("Move Right");

        sImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\jalpd\\Downloads\\BombermanFinal(1)\\BombermanFinal\\payload\\Keys\\s.png")); // NOI18N

        sDescription.setText("Move Down");

        wImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\jalpd\\Downloads\\BombermanFinal(1)\\BombermanFinal\\payload\\Keys\\w.png")); // NOI18N

        wDescription.setText("Move Up");

        mainTitle.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        mainTitle.setText("Game Instructions");

        spaceImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\jalpd\\Downloads\\BombermanFinal(1)\\BombermanFinal\\payload\\Keys\\space.png")); // NOI18N

        spaceDescription.setText("Deploy Bomb");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(mainTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(wImage)
                            .addComponent(sImage)
                            .addComponent(dImage)
                            .addComponent(aImage))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aDescription)
                            .addComponent(wDescription)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dDescription)
                                    .addComponent(sDescription))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                                .addComponent(backButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(spaceImage)
                        .addGap(18, 18, 18)
                        .addComponent(spaceDescription)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aImage)
                    .addComponent(aDescription))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dImage)
                            .addComponent(dDescription))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sImage)
                            .addComponent(sDescription)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(backButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wImage)
                    .addComponent(wDescription))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spaceImage)
                    .addComponent(spaceDescription))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameInstructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameInstructions dialog = new GameInstructions(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aDescription;
    private javax.swing.JLabel aImage;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dDescription;
    private javax.swing.JLabel dImage;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JLabel sDescription;
    private javax.swing.JLabel sImage;
    private javax.swing.JLabel spaceDescription;
    private javax.swing.JLabel spaceImage;
    private javax.swing.JLabel wDescription;
    private javax.swing.JLabel wImage;
    // End of variables declaration//GEN-END:variables
}
